Web_BanXeMoTo/Models/MauXe.cs
using Microsoft.AspNetCore.Http;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace Web_BanXeMoTo.Models
{
    public partial class MauXe
    {
        public MauXe()
        {
            ChiTietDgs = new HashSet<ChiTietDg>();
            DatLiches = new HashSet<DatLich>();
            Xes = new HashSet<Xe>();
        }

        [Display(Name = "ID mẫu xe")]
        [Required(ErrorMessage = "Không được bỏ trống, không được trùng lặp")]
        public string Idmau { get; set; }

        [Display(Name = "Khuyến mãi (%)")]
        public string Idkm { get; set; }

        [Display(Name = "Hãng xe")]
        public string Idhang { get; set; }

        [Display(Name = "Tên xe")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string TenXe { get; set; }

        [Display(Name = "Giá bán")]
        [Range(1000, 9999999999999999999, ErrorMessage = "Giá bán phải lớn hơn 1000VNĐ")]
        public decimal GiaBan { get; set; }

        [Display(Name = "Hình 1")]
        public string HinhAnh1 { get; set; }

        [Display(Name = "Hình 2")]
        public string HinhAnh2 { get; set; }

        [Display(Name = "Hình 3")]
        public string HinhAnh3 { get; set; }

        [Display(Name = "Bảo hành")]
        [Range(1, 36, ErrorMessage = "Chỉ bảo hành từ 1 đến 36 tháng")]
        public int BaoHanh { get; set; }

        [Display(Name = "Mô tả")]
        [Required(ErrorMessage = "Không được bỏ trống")]
        public string MoTa { get; set; }

        //true là đang kinh doanh, false là ngừng kinh doanh
        [Display(Name = "Trạng thái")]
        public bool? TrangThai { get; set; }

        public virtual Hang IdhangNavigation { get; set; }
        public virtual KhuyenMai IdkmNavigation { get; set; }
        public virtual ICollection<ChiTietDg> ChiTietDgs { get; set; }
        public virtual ICollection<DatLich> DatLiches { get; set; }
        public virtual ICollection<Xe> Xes { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Hãy chọn hình")]
        public IFormFile UploadHinh1 { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Hãy chọn hình")]
        public IFormFile UploadHinh2 { get; set; }
        [NotMapped]
        [Required(ErrorMessage = "Hãy chọn hình")]
        public IFormFile UploadHinh3 { get; set; }


    }
}

Web_BanXeMoTo/Controllers/MauXeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using X.PagedList;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Web_BanXeMoTo.Models;

namespace Web_BanXeMoTo.Controllers
{
    [Authorize(Roles = "admin")]
    public class MauXeController : Controller
    {
        private readonly QLMoToContext database;
        private readonly IWebHostEnvironment hostEnvironment;
        
        public MauXeController(QLMoToContext db, IWebHostEnvironment hostEnvironment)
        {
            database = db;
            this.hostEnvironment = hostEnvironment;
        }
        //public IActionResult Index()
        //{
        //    ViewBag.Role = TempData["Role"];

        //    var model = new ViewModel();
        //    model.ListHang = database.Hangs.ToArray();
        //    model.ListMauXe = database.MauXes.ToList();
        //    model.ListKhuyenMai = database.KhuyenMais.ToArray();
        //    return View(model);
        //}

        public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            //A ViewBag property provides the view with the current sort order, because this must be included in 
            //  the paging links in order to keep the sort order the same while paging
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

                ViewBag.Role = TempData["Role"];

            var ModelList = new List<MauXe>();

            //ViewBag.CurrentFilter, provides the view with the current filter string.
            //he search string is changed when a value is entered in the text box and the submit button is pressed. In that case, the searchString parameter is not null.
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;


            using (var context = new QLMoToContext())
            {
                var model = from s in context.MauXes
                            select s;
                //Search and match data, if search string is not null or empty
                if (!String.IsNullOrEmpty(searchString))
                {
                    model = model.Where(s => s.Idmau.Contains(searchString)
                                           || s.Idhang.Contains(searchString)
                                           || s.TenXe.Contains(searchString));
                }
                switch (sortOrder)
                {
                    case "name_desc":
                        ModelList = model.OrderByDescending(s => s.TenXe).ToList();
                        break;

                    default:
                        ModelList = model.OrderBy(s => s.TenXe).ToList();
                        break;
                }

            }
            //indicates the size of list
            int pageSize = 10;
            //set page to one is there is no value, ??  is called the null-coalescing operator.
            int pageNumber = (page ?? 1);
            //return the Model data with paged
            var modelv = new ViewModel
            {
                ListHang = database.Hangs.ToArray(),
                ListXe = database.Xes.ToArray(),
                ListMauXes = ModelList.ToPagedList(pageNumber, pageSize),
                ListKhuyenMai = database.KhuyenMais.ToArray()
            };
            return View(modelv);
        }

        public IActionResult Create()
        {
            ViewBag.Role = TempData["Role"];

            var model = new ViewModel();
            model.ListHang = database.Hangs.ToArray();
            model.ListKhuyenMai = database.KhuyenMais.ToArray();
            return View(model);
        }


        [HttpPost]
        public async Task<IActionResult> Create(MauXe mauXe)
        {
            var model = new ViewModel();
            model.ListHang = database.Hangs.ToArray();
            model.ListKhuyenMai = database.KhuyenMais.ToArray();
            if (ModelState.IsValid)
            {
                #region Save Image from wwwroot/img
                string wwwRootPath = hostEnvironment.WebRootPath;
                string fileName1 = Path.GetFileNameWithoutExtension(mauXe.UploadHinh1.FileName);
                string fileName2 = Path.GetFileNameWithoutExtension(mauXe.UploadHinh2.FileName);
                string fileName3 = Path.GetFileNameWithoutExtension(mauXe.UploadHinh3.FileName);

                string extension1 = Path.GetExtension(mauXe.UploadHinh1.FileName);
                string extension2 = Path.GetExtension(mauXe.UploadHinh2.FileName);
                string extension3 = Path.GetExtension(mauXe.UploadHinh3.FileName);

                mauXe.HinhAnh1 = "/img/" + fileName1 + extension1;
                mauXe.HinhAnh2 = "/img/" + fileName2 + extension2;
                mauXe.HinhAnh3 = "/img/" + fileName3 + extension3;

                string path1 = Path.Combine(wwwRootPath + "/img/", fileName1);
                string path2 = Path.Combine(wwwRootPath + "/img/", fileName2);
                string path3 = Path.Combine(wwwRootPath + "/img/", fileName3);


                using (var fileStream = new FileStream(path1, FileMode.Create))
                {
                    await mauXe.UploadHinh1.CopyToAsync(fileStream);
                }
                using (var fileStream = new FileStream(path2, FileMode.Create))
                {
                    await mauXe.UploadHinh2.CopyToAsync(fileStream);
                }
                using (var fileStream = new FileStream(path3, FileMode.Create))
                {
                    await mauXe.UploadHinh3.CopyToAsync(fileStream);
                }
                #endregion

                database.Add(mauXe);
                await database.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Details(string id)
        {
            ViewBag.Role = TempData["Role"];

            var model = new ViewModel();
            model.ListHang = database.Hangs.ToArray();
            model.ListKhuyenMai = database.KhuyenMais.ToArray();
            model.mauXe = database.MauXes.Where(x => x.Idmau == id).FirstOrDefault();
            return View(model);
        }

        public IActionResult Delete(string id)
        {
            ViewBag.Role = TempData["Role"];

            var model = new ViewModel();
            model.ListHang = database.Hangs.ToArray();
            model.ListKhuyenMai = database.KhuyenMais.ToArray();
            model.mauXe = database.MauXes.Where(x => x.Idmau == id).FirstOrDefault();
            return View(model);
        }

        [HttpPost]
        public IActionResult Delete(string id,MauXe mauXe)
        {
            mauXe = database.MauXes.Where(x => x.Idmau == id).FirstOrDefault();
            database.Remove(mauXe);
            database.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Edit(string id)
        {
            ViewBag.Role = TempData["Role"];

            var model = new ViewModel();
            model.ListHang = database.Hangs.ToArray();
            model.ListMauXe = database.MauXes.ToArray();
            model.ListKhuyenMai = database.KhuyenMais.ToArray();
            model.mauXe = database.MauXes.Where(x => x.Idmau == id).FirstOrDefault();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(string id,MauXe mauXe)
        {
            var model = new ViewModel();
            model.ListHang = database.Hangs.ToArray();
            model.ListKhuyenMai = database.KhuyenMais.ToArray();
            model.mauXe = database.MauXes.Where(x => x.Idmau == id).FirstOrDefault();
            if(mauXe.TenXe != null && mauXe.MoTa != null && mauXe.BaoHanh > 0 && mauXe.GiaBan >= 1000)
            {
                model.mauXe.TenXe = mauXe.TenXe;
                model.mauXe.Idhang = mauXe.Idhang;
                model.mauXe.Idkm = mauXe.Idkm;
                model.mauXe.BaoHanh = mauXe.BaoHanh;
                model.mauXe.GiaBan = mauXe.GiaBan;
                model.mauXe.MoTa = mauXe.MoTa;
                model.mauXe.TrangThai = mauXe.TrangThai;

                #region Save Image from wwwroot/img
                string wwwRootPath = hostEnvironment.WebRootPath;

                string fileName1, fileName2, fileName3;
                string extension1, extension2, extension3;
                if (mauXe.UploadHinh1 != null)
                {
                    fileName1 = Path.GetFileNameWithoutExtension(mauXe.UploadHinh1.FileName);
                    extension1 = Path.GetExtension(mauXe.UploadHinh1.FileName);
                    model.mauXe.HinhAnh1 = "/img/" + fileName1 + extension1;
                    string path1 = Path.Combine(wwwRootPath + "/img/", fileName1);
                    using (var fileStream = new FileStream(path1, FileMode.Create))
                    {
                        await mauXe.UploadHinh1.CopyToAsync(fileStream);
                    }
                }
                if (mauXe.UploadHinh2 != null)
                {
                    fileName2 = Path.GetFileNameWithoutExtension(mauXe.UploadHinh2.FileName);
                    extension2 = Path.GetExtension(mauXe.UploadHinh2.FileName);
                    model.mauXe.HinhAnh2 = "/img/" + fileName2 +  extension2;
                    string path2 = Path.Combine(wwwRootPath + "/img/", fileName2);

Web_BanXeMoTo/Views/MauXe/Create.cshtml
@model Web_BanXeMoTo.Controllers.ViewModel



@{
    ViewData["Title"] = "Create";

    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}


<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Mẫu xe

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link  ">
                <span>Mẫu xe</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="Create" class="nav-link active">
                <span>Thêm mẫu xe</span>
            </a>


        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="mauXe.Idmau" class="control-label"></label>
                            <input asp-for="mauXe.Idmau" class="form-control" />
                            <span asp-validation-for="mauXe.Idmau" class="text-danger"></span>
                        </div>
                        <partial name="_FormEdit" model="Model" />
                        <div class="form-group">
                            <input type="submit" value="Thêm" class="btn btn-primary" />
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

Web_BanXeMoTo/Views/MauXe/Delete.cshtml
@model Web_BanXeMoTo.Controllers.ViewModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}

<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Mẫu xe

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link">
                <span>Mẫu xe</span>
            </a>
        </li>

    </ul>
    <div class="row">
        <div class="col-md-10">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <div>
                        <partial name="_ListDetails" model="Model" />
                        <hr/>
                        <form asp-action="Delete">
                            <input type="submit" value="Xóa" class="btn btn-sm btn-danger" /> |
                            <a asp-action="Index" class="btn btn-sm btn-outline-secondary">Trở về</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Web_BanXeMoTo/Views/MauXe/Details.cshtml
@model Web_BanXeMoTo.Controllers.ViewModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}

<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Mẫu xe

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link">
                <span>Mẫu xe</span>
            </a>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-10">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <div>
                        <partial name="_ListDetails" model="Model"/>
                    </div>
                    <hr />
                    <div class="form-group">
                        <a asp-action="Edit" asp-route-id="@Model.mauXe.Idmau" class="btn btn-sm btn-outline-warning">Sửa</a>
                        <a asp-action="Index" class="btn btn-sm btn-outline-secondary">Trở về</a>
                    </div>
                </div>
        </div>
    </div>
</div>

Web_BanXeMoTo/Views/MauXe/Edit.cshtml
@model Web_BanXeMoTo.Controllers.ViewModel



@{
    ViewData["Title"] = "Edit";

    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}


<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Mẫu xe

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link">
                <span>Mẫu xe</span>
            </a>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <form asp-action="Edit" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="mauXe.Idmau" class="control-label"></label>
                            <input asp-for="mauXe.Idmau" class="form-control" readonly />
                            <span asp-validation-for="mauXe.Idmau" class="text-danger"></span>
                        </div>
                        <partial name="_FormEdit" model="Model" />
                        <div class="form-group">
                            <input type="submit" value="Lưu" class="btn btn-sm btn-outline-primary" />
                            <a asp-action="Details" asp-route-id="@Model.mauXe.Idmau" class="btn btn-sm btn-outline-info">Chi tiết</a>
                            <a asp-action="Index" class="btn btn-sm btn-outline-secondary">Trở về</a>
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

Web_BanXeMoTo/Views/MauXe/Index.cshtml
@{ ViewData["Tittle"] = "Danh sách mẫu xe";
    Layout = "~/Views/Shared/_LayoutManager.cshtml"; }

@model Web_BanXeMoTo.Controllers.ViewModel
@using X.PagedList.Mvc.Core;
@using Microsoft.AspNetCore.Mvc;

<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Mẫu xe

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link active ">
                <span>Mẫu xe</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="Create" class="nav-link ">
                <span>Thêm mẫu xe</span>
            </a>


        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    @using (Html.BeginForm("Index", "MauXe", FormMethod.Get, new { @style = "float: right; width: 40%" }))
                    {
                        <input type="text" id="searchString" name="searchString" placeholder="Find by id or name">
                        <input type="submit" value="Search" class="btn btn-outline-info" style="margin-bottom:5px" />
                    }
                    <br />
                    <table class="table table-hover table-sm">
                        <thead>
                            <tr>
                                <th>
                                    <label class="control-label">@Html.ActionLink("ID Mẫu", "Index", new { sortOrder = ViewBag.NameSortParm })</label>
                                </th>
                                <th>
                                    <label class="control-label">Hình</label>
                                </th>
                                <th>
                                    <label asp-for="mauXe.TenXe" class="control-label"></label>
                                </th>

                                <th>
                                    <label asp-for="hang.TenHang" class="control-label"></label>
                                </th>

                                <th>
                                    <label asp-for="mauXe.GiaBan" class="control-label"></label>
                                </th>
                                <th class="text-center">
                                    <label asp-for="mauXe.BaoHanh" class="control-label"></label>
                                </th>
                                <th class="text-center">
                                    <label class="control-label">Khuyến mãi</label>
                                </th>
                                <th class="text-center">
                                    <label class="control-label">Số lượng</label>
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ListMauXes)
                            {
                <tr>
                    <td>
                        @item.Idmau
                    </td>
                    <td>
                        <img src="@item.HinhAnh1" width="120" height="90" />
                    </td>
                    <td>
                        @item.TenXe
                    </td>
                    <td>
                        @foreach (var hang in Model.ListHang)
                        {
                            if (hang.Idhang == item.Idhang)
                            {
                                @hang.TenHang
                                break;
                            }
                        }
                    </td>

                    <td>
                        @((int)@item.GiaBan) VNĐ
                    </td>
                    <td class="text-center">
                        @item.BaoHanh
                    </td>
                    <td class="text-center">
                        @foreach (var khuyenmai in Model.ListKhuyenMai)
                        {
                            if (khuyenmai.Idkm == item.Idkm)
                            {
        @khuyenmai.GiaTri break;
    }
}%
                    </td>
                    <td class="text-center">
                        @{ int amount = 0;
                            @foreach (var mauxe in Model.ListXe)
                            {
                                if (mauxe.Idmau == item.Idmau)
                                {
                                    amount++;
                                }
                            }
                                            @amount }
                    </td>
                    <td>
                        <a asp-action="Details" asp-route-id="@item.Idmau" class="btn btn-sm btn-outline-info">Chi tiết</a>
                        <a asp-action="Delete" asp-route-id="@item.Idmau" class="btn btn-sm btn-outline-danger" hidden>Xóa</a>
                        <a asp-action="Edit" asp-route-id="@item.Idmau" class="btn btn-sm btn-outline-warning">Sửa</a>
                    </td>
                </tr>
}
                        </tbody>
                    </table>

                    @Html.PagedListPager(Model.ListMauXes, page => Url.Action("Index",
                                                      new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
                </div>
            </div>
        </div>
    </div>

</div>

Web_BanXeMoTo/Views/MauXe/_FormEdit.cshtml
@model Web_BanXeMoTo.Controllers.ViewModel



<div class="form-group">
    <label asp-for="mauXe.TenXe" class="control-label"></label>
    <input asp-for="mauXe.TenXe" class="form-control" />
    <span asp-validation-for="mauXe.TenXe" class="text-danger"></span>
</div>
<div class="position-relative form-group">
    <label asp-for="mauXe.Idkm" class="control-label"></label>
    <select asp-for="mauXe.Idkm" class="form-control">
        @foreach (var item in Model.ListKhuyenMai)
        {
            <option value="@item.Idkm">@item.GiaTri </option>
        }
    </select>
</div>
<div class="position-relative form-group">
    <label asp-for="mauXe.Idhang" class="control-label"></label>
    <select asp-for="mauXe.Idhang" class="form-control">
        @foreach (var item in Model.ListHang)
        {
            <option value="@item.Idhang">@item.TenHang</option>
        }
    </select>
</div>

<div class="form-group">
    <label asp-for="mauXe.GiaBan" class="control-label"></label>
    <input asp-for="mauXe.GiaBan" class="form-control" />
    <span asp-validation-for="mauXe.GiaBan" class="text-danger"></span>
</div>

<div class="form-group">
    <label asp-for="mauXe.BaoHanh" class="control-label"></label>
    <input asp-for="mauXe.BaoHanh" class="form-control" />
    <span asp-validation-for="mauXe.BaoHanh" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="mauXe.TrangThai" class="control-label"></label>
    <select asp-for="mauXe.TrangThai" class="form-control">
        <option value="true">Đang kinh doanh</option>
        <option value="false">Ngừng kinh doanh</option>
    </select>    <span asp-validation-for="mauXe.TrangThai" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="mauXe.MoTa" class="control-label"></label>
    <input asp-for="mauXe.MoTa" class="form-control" />
    <span asp-validation-for="mauXe.MoTa" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="mauXe.UploadHinh1" class="control-label"></label>
    <input asp-for="mauXe.UploadHinh1" accept="image/*" />
    @if (Model.mauXe != null)
    {
        <img src="@Model.mauXe.HinhAnh1" asp-append-version="true" width="120" height="90" />
    }
    <span asp-validation-for="mauXe.UploadHinh1" class="text-danger" hidden></span>
</div>
<div class="form-group">
    <label asp-for="mauXe.UploadHinh2" class="control-label"></label>
    <input asp-for="mauXe.UploadHinh2" accept="image/*" />
    @if (Model.mauXe != null)
    {
        <img src="@Model.mauXe.HinhAnh2" asp-append-version="true" width="120" height="90" />
    }
    <span asp-validation-for="mauXe.UploadHinh2" class="text-danger" hidden></span>
</div>
<div class="form-group">
    <label asp-for="mauXe.UploadHinh3" class="control-label"></label>
    <input asp-for="mauXe.UploadHinh3" accept="image/*" />
    @if (Model.mauXe != null)
    {
        <img src="@Model.mauXe.HinhAnh3" asp-append-version="true" width="120" height="90" />
    }
    <span asp-validation-for="mauXe.UploadHinh3" class="text-danger" hidden></span>
</div>

Web_BanXeMoTo/Views/MauXe/_ListDetails.cshtml
@model Web_BanXeMoTo.Controllers.ViewModel

<dl class="row">
    <dt class="col-md-2">
        <label asp-for="mauXe.Idmau" class="control-label"></label>
    </dt>

    <dd class="col-md-10">
        @Model.mauXe.Idmau
    </dd>
    <dt class="col-md-2">
        <label asp-for="mauXe.Idkm" class="control-label"></label>

    </dt>
    <dd class="col-md-10">
        @foreach (var khuyenmai in Model.ListKhuyenMai)
        {
            if (khuyenmai.Idkm == @Model.mauXe.Idkm)
            {
                @khuyenmai.GiaTri
                break;
            }
        }%
    </dd>
    <dt class="col-md-2">
        <label asp-for="mauXe.Idhang" class="control-label"></label>
    </dt>
    <dd class="col-md-10">
        @foreach (var hang in Model.ListHang)
        {
            if (hang.Idhang == @Model.mauXe.Idhang)
            {
                @hang.TenHang
                break;
            }
        }
    </dd>
    <dt class="col-md-2">
        <label asp-for="mauXe.TenXe" class="control-label"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.mauXe.TenXe
    </dd>
    <dt class="col-sm-2">
        <label asp-for="mauXe.GiaBan" class="control-label"></label>
    </dt>
    <dd class="col-sm-10">
        @((int)@Model.mauXe.GiaBan) VNĐ
    </dd>
    <dt class="col-sm-2">
        <label asp-for="mauXe.BaoHanh" class="control-label"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.mauXe.BaoHanh tháng
    </dd>
    <dt class="col-sm-2">
        <label asp-for="mauXe.MoTa" class="control-label"></label>
    </dt>
    <dd class="col-sm-10">
        @Model.mauXe.MoTa
    </dd>
    <dt class="col-sm-2">
        <label asp-for="mauXe.HinhAnh1" class="control-label"></label>
    </dt>
    <dd class="col-sm-10">
        <img src="@Model.mauXe.HinhAnh1" asp-append-version="true" width="200" height="150" />
    </dd>
    <dt class="col-sm-2">
        <label asp-for="mauXe.HinhAnh2" class="control-label"></label>
    </dt>
    <dd class="col-sm-10">
        <img src="@Model.mauXe.HinhAnh2" asp-append-version="true" width="200" height="150" />
    </dd>
    <dt class="col-sm-2">
        <label asp-for="mauXe.HinhAnh3" class="control-label"></label>
    </dt>
    <dd class="col-sm-10">
        <img src="@Model.mauXe.HinhAnh3" asp-append-version="true" width="200" height="150" />
    </dd>
</dl>