Web_BanXeMoTo/Models/HoaDon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace Web_BanXeMoTo.Models
{
    public partial class HoaDon
    {
        public HoaDon()
        {
            ChiTietHds = new HashSet<ChiTietHd>();
        }

        [Display(Name = "ID hóa đơn")]
        public string Idhd { get; set; }

        [Display(Name = "ID khách hàng")]
        public int Idkh { get; set; }

        [Display(Name = "Ngày đặt")]
        public DateTime NgayDat { get; set; }

        public virtual KhachHang IdkhNavigation { get; set; }

        [Display(Name = "Chi tiết hóa đơn")]
        public virtual ICollection<ChiTietHd> ChiTietHds { get; set; }
    }
}

Web_BanXeMoTo/Controllers/HoaDonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Web_BanXeMoTo.Models;
using X.PagedList;

namespace Web_BanXeMoTo.Controllers
{
    [Authorize(Roles = "admin, staff")]
    public class HoaDonController : Controller
    {
        private readonly QLMoToContext database;

        public HoaDonController(QLMoToContext db)
        {
            database = db;
        }
        public IActionResult Index( int? page)
        {
            var ModelList = database.HoaDons.ToList();
            int pageSize = 10;
            //set page to one is there is no value, ??  is called the null-coalescing operator.
            int pageNumber = (page ?? 1);
            //return the Model data with paged
            var modelv = new HoaDonViewModel
            {
                HoaDons = ModelList.ToPagedList(pageNumber, pageSize),
                ListChiTietHd = database.ChiTietHds.ToArray(),
                ListKhachHang = database.KhachHangs.ToArray()
            };
            return View(modelv);
        }

        public IActionResult Create()
        {
            var model = new HoaDonViewModel
            {
                HoaDon = new HoaDon { Idhd = GetIDHD() },
                ListKhachHang = database.KhachHangs.ToArray()
            };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(HoaDon hoaDon)
        {
            if (ModelState.IsValid)
            {
                database.HoaDons.Add(hoaDon);
                await database.SaveChangesAsync();
                return RedirectToAction("CTHD", new { ID = hoaDon.Idhd });
            }
            return View(hoaDon);
        }
        public IActionResult Details(string ID)
        {
            var model = new HoaDonViewModel
            {
                ChiTietHd = new ChiTietHd { Idhd = ID },
                ListChiTietHd = database.ChiTietHds.Where(x=>x.Idhd == ID).ToArray(),
            };
            return View(model);
        }

        public async Task<IActionResult> CTHD(string ID)
        {
            var model = new HoaDonViewModel
            {
                ChiTietHd = new ChiTietHd { Idhd = ID },
                ListMauXe = database.MauXes.ToArray(),
                ListXe = database.Xes.Where(x=>x.TrangThai == true).ToArray(),
            };
            foreach (var mauxe in model.ListMauXe)
            {
                mauxe.IdhangNavigation = await database.Hangs.Where(x => x.Idhang == mauxe.Idhang).FirstOrDefaultAsync();
            }
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> CTHD(ChiTietHd chiTietHd)
        {
            try
            {
                var Xe = await database.Xes.Where(x => x.Idxe == chiTietHd.Idxe).FirstOrDefaultAsync();
                var MauXe = await database.MauXes.Where(x => x.Idmau == Xe.Idmau).Select(x => new { x.GiaBan, x.Idkm }).FirstOrDefaultAsync();
                var KhuyenMai = await database.KhuyenMais.Where(x => x.Idkm == MauXe.Idkm).Select(x => x.GiaTri).FirstOrDefaultAsync();

                Xe.TrangThai = false;
                database.Xes.Update(Xe);

                chiTietHd.KhuyenMai = KhuyenMai;
                chiTietHd.GiaBan = MauXe.GiaBan;
                database.ChiTietHds.Add(chiTietHd);
                await database.SaveChangesAsync();
                return RedirectToAction("Details", new { ID = chiTietHd.Idhd });
            }
            catch
            {
                ViewBag.Error = "Xe đã có trong hóa đơn!";
                var model = new HoaDonViewModel
                {
                    ChiTietHd = chiTietHd,
                    ListMauXe = database.MauXes.ToArray(),
                    ListXe = database.Xes.ToArray(),
                };
                foreach (var mauxe in model.ListMauXe)
                {
                    mauxe.IdhangNavigation = await database.Hangs.Where(x => x.Idhang == mauxe.Idhang).FirstOrDefaultAsync();
                }
                return View(model);
            }
        }
        public async Task<IActionResult> DeleteCTHD(string idXe, string idHD)
        {
            var Xe = await database.Xes.Where(x => x.Idxe == idXe).FirstOrDefaultAsync();
            var ChiTietHD = await database.ChiTietHds.Where(x => x.Idhd == idHD && x.Idxe == idXe).FirstOrDefaultAsync();
            database.Remove(ChiTietHD);
            await database.SaveChangesAsync();
            return RedirectToAction("Details", new { ID = idHD });
        }
        public string GetIDHD()
        {
            var list = database.HoaDons.ToArray();

            int.TryParse(list[list.Length - 1].Idhd.Substring(2), out int lastID);

            string ID = "HD" + ++lastID;

            return ID;
        }
    }
    public class HoaDonViewModel
    {
        public KhuyenMai[] ListKhuyenMai { get; set; }
        public Xe[] ListXe { get; set; }
        public MauXe[] ListMauXe { get; set; }
        public KhachHang[] ListKhachHang { get; set; }
        public ChiTietHd ChiTietHd { get; set; }
        public ChiTietHd[] ListChiTietHd { get; set; }
        public HoaDon HoaDon { get; set; }
        public HoaDon[] ListHoaDon { get; set; }
        public IPagedList<HoaDon> HoaDons { get; set; }
    }
}

Web_BanXeMoTo/Views/HoaDon/CTHD.cshtml
@model Web_BanXeMoTo.Controllers.HoaDonViewModel

@{
    ViewData["Title"] = "Tạo chi tiết hóa đơn";
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}


<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Hóa đơn

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link  ">
                <span>Danh sách hóa đơn</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="Create" class="nav-link ">
                <span>Tạo hóa đơn</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="CTHD" class="nav-link active ">
                <span>Thêm xe</span>
            </a>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <form asp-action="CTHD">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="ChiTietHd.Idhd" class="control-label"></label>
                            <input asp-for="ChiTietHd.Idhd" class="form-control" readonly />
                            <span asp-validation-for="ChiTietHd.Idhd" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label class="control-label"> Xe </label>
                            <select asp-for="ChiTietHd.Idxe" class="form-control">
                                @foreach (var mauXe in Model.ListMauXe)
                                {
                                    <option disabled style="font-weight:900">- @mauXe.IdhangNavigation.TenHang :&emsp;@mauXe.TenXe </option>
                                    @foreach (var xe in Model.ListXe)
                                    {
                                        if (mauXe.Idmau == xe.Idmau && xe.TrangThai == true)
                                        {
                                            <option value="@xe.Idxe">&emsp;&emsp;+ @xe.Idxe</option>
                                        }
                                    }
                                }
                            </select>
                            <span class="text-danger">@ViewBag.Error</span>

                        </div>
                        @*<div class="form-group">
            <label asp-for="ChiTietHd.KhuyenMai" class="control-label"></label>
            <input asp-for="ChiTietHd.KhuyenMai" class="form-control" readonly value="" >
            <span asp-validation-for="ChiTietHd.KhuyenMai" class="text-danger"></span>
        </div>
        <div class="form-group">
            <label asp-for="ChiTietHd.GiaBan" class="control-label"></label>
            <input asp-for="ChiTietHd.GiaBan" class="form-control" readonly value=""/>
            <span asp-validation-for="ChiTietHd.GiaBan" class="text-danger"></span>
        </div>*@
                    <div class="form-group">
                        <input type="submit" value="Thêm xe vào hóa đơn" class="btn btn-primary" />
                        <a asp-action="Details" asp-route-id="@Model.ChiTietHd.Idhd" class="btn btn-secondary">Trở về</a>
                    </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

Web_BanXeMoTo/Views/HoaDon/Create.cshtml
@model Web_BanXeMoTo.Controllers.HoaDonViewModel

@{
    ViewData["Title"] = "Tạo hóa đơn";

    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}


<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Hóa đơn

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link  ">
                <span>Danh sách hóa đơn</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="Create" class="nav-link active">
                <span>Tạo hóa đơn</span>
            </a>


        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <form asp-action="Create" enctype="multipart/form-data">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="HoaDon.Idhd" class="control-label"></label>
                            <input asp-for="HoaDon.Idhd" class="form-control" readonly />
                            <span asp-validation-for="HoaDon.Idhd" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="HoaDon.Idkh" class="control-label"></label>
                            <select asp-for="HoaDon.Idkh" class="form-control">
                                @foreach (var item in Model.ListKhachHang)
                                {
                                    <option value="@item.Idkh"><span style="font-weight:900">ID: @item.Idkh </span>&emsp;@item.TenKh</option>
                                }
                            </select>
                        </div>
                        <div class="form-group">
                            <label asp-for="HoaDon.NgayDat" class="control-label"></label>
                            <input asp-for="HoaDon.NgayDat" class="form-control" value="0001-01-01T" />
                            <span asp-validation-for="HoaDon.NgayDat" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Tạo hóa đơn" class="btn btn-primary" />
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>

Web_BanXeMoTo/Views/HoaDon/Details.cshtml
@model Web_BanXeMoTo.Controllers.HoaDonViewModel

@{
    ViewData["Title"] = "Chi tiết hóa đơn";
    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}

<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Hóa đơn

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link active">
                <span>Danh sách hóa đơn</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="Create" class="nav-link ">
                <span>Tạo hóa đơn</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="CTHD" class="nav-link " asp-route-id="@Model.ChiTietHd.Idhd">
                <span>Thêm xe</span>
            </a>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <table class="table table-hover table-sm">
                        <h3>ID Hóa đơn: @Model.ChiTietHd.Idhd</h3>
                        <br/>
                        <thead>
                            <tr>

                                <th>
                                    <label asp-for="ChiTietHd.Idxe" class="control-label"></label>
                                </th>
                                <th>
                                    <label asp-for="ChiTietHd.KhuyenMai" class="control-label"></label>
                                </th>

                                <th>
                                    <label asp-for="ChiTietHd.GiaBan" class="control-label"></label>
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ListChiTietHd)
                            {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Idxe)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.KhuyenMai)
                                    </td>
                                    <td>
                                        @string.Format("{0:N0}", ((Int64)item.GiaBan)) VNĐ
                                    </td>
                                    <td>
                                        @Html.ActionLink("Edit", "HoaDon", new { /* id=item.PrimaryKey */ })
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Web_BanXeMoTo/Views/HoaDon/Index.cshtml
@model Web_BanXeMoTo.Controllers.HoaDonViewModel

@{
    ViewData["Title"] = "Create";

    Layout = "~/Views/Shared/_LayoutManager.cshtml";
}


<div class="app-main__inner">
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div>

                    Quản lý Hóa đơn

                </div>
            </div>
        </div>
    </div>
    <ul class="body-tabs body-tabs-layout tabs-animated body-tabs-animated nav">
        <li class="nav-item">
            <a asp-action="Index" class="nav-link active ">
                <span>Danh sách hóa đơn</span>
            </a>
        </li>
        <li class="nav-item">
            <a asp-action="Create" class="nav-link ">
                <span>Tạo hóa đơn</span>
            </a>
        </li>
    </ul>
    <div class="row">
        <div class="col-md-12">
            <div class="main-card mb-3 card">
                <div class="card-body">
                    <table class="table table-hover table-sm">
                        <thead>
                            <tr>
                                <th>
                                    <label asp-for="HoaDon.Idhd" class="control-label"></label>
                                </th>

                                <th>
                                    <label asp-for="HoaDon.IdkhNavigation.TenKh" class="control-label"></label>
                                </th>

                                <th>
                                    <label asp-for="HoaDon.NgayDat" class="control-label"></label>
                                </th>
                                <th>
                                    <label class="control-label">Tổng tiền</label>
                                </th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ListHoaDon)
                            {
                                <tr>
                                    <td>
                                        @item.Idhd
                                    </td>

                                    <td>
                                        @foreach (var kh in Model.ListKhachHang)
                                        {

                                            if (item.Idkh == kh.Idkh)
                                            {
                                                @kh.TenKh
                                            }
                                        }
                                    </td>
                                    <td>
                                        @item.NgayDat
                                    </td>
                                    <td>
                                        @{
                                            Int64 amount = 0;
                                            @foreach (var cthd in Model.ListChiTietHd)
                                            {

                                                if (item.Idhd == cthd.Idhd)
                                                {
                                                    amount += (Int64)cthd.GiaBan * ((int)((cthd.KhuyenMai != 0) ? cthd.KhuyenMai / 100 : 1) );
                                                }
                                            }
                                            @string.Format("{0:N0}", ((Int64)@amount)) 

                                        } VNĐ
                                    </td>
                                    <td>
                                        <a asp-action="Details" asp-route-id="@item.Idhd" class="btn btn-sm btn-outline-info">Chi tiết</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>